### PR TITLE
Avoid timeout when checking for stale issues/pull requests

### PR DESCRIPTION
**Pull request by astrofrog**
As described in https://librenepal.com/article/flask-and-heroku-timeout/, this should prevent timeouts as well as return the status of the checks to Travis

### CODE REVIEW

**Comment by pllim** [comment]
This broke the tests. 😢

**Comment by bsipocz** [comment]
Wow, this really messed up the tests. Could you please fix them?

**Comment by astrofrog** [comment]
I'll get to it soon...

**Comment by pllim** [comment]
(Would be nice to resolve this one before refactoring for #2, #58, and such.)

**Review by pllim — APPROVED** [review]
LGTM but need a rebase and reinspect CI results *after* merging #70.

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
