### PR TITLE
Migrate to baldrick

### PR DESCRIPTION
**Pull request by astrofrog**
### Background

@Cadair and I have generalized most of the astropy-bot code and moved it over to a new package called [baldrick](https://github.com/astrofrog/baldrick) (we can discuss which org to move it to later). The idea is that baldrick is an installable Python package that provides all the infrastructure needed to set up bots such as astropy-bot, giles, and the sunpy bot, in the form of a function to create the app, and a set of blueprints and plugins for those blueprints. We'll be writing some docs for baldrick shortly.

The astropy-bot will then contain any code that is specific to the astropy project as well as the files required to set up the Heroku app.

@pllim and @bsipocz, I'll add you shortly as maintainers for baldrick

### This PR

The only plugin that is Astropy-specific is the changelog checker since it is specific to how we organize the changelog, and therefore this is the only main piece of code that remains here. I've also factored out the actual parsing of the changelog into a separate package called [astropy-changelog](https://github.com/astrofrog/astropy-changelog). The intent is to try and formalize the format(s) we use beyond just the bot, and to use that parser here.

### The plan

I need to deploy a test version of this bot to make sure it works correctly on a test repo before we actually merge this. We also need to improve the test coverage for baldrick first. Once these things are done, we can make releases of baldrick and astropy-changelog, update the dependencies in this PR, and merge.

To dos:

* [x] Release baldrick
* [x] Release astropy-changebot
* [x] Update dependencies to point to stable versions
* [x] Try out bot on Heroku
* [x] Update README

### Going forward

The way we've refactored baldrick actually allows us to switch to a model where we only post statuses rather than a comment with a list of issues. This may be preferable? (we don't have to decide this now).

### CODE REVIEW

**Comment by pllim** [comment]
> we can discuss which org to move it to later

Too bad github.com/blackadder is already taken

> where we only post statuses

Does "status" work for issues, or is this particular change specific to PR?

**Comment by astrofrog** [comment]
> Does "status" work for issues, or is this particular change specific to PR?

I just meant for the PRs - there is no way to have a status on an issue.

**Comment by astrofrog** [comment]
I've tested the PR review capability on Heroku and it seems to work :)

Next step is to check the stale PR/issue functionality.

**Comment by astrofrog** [comment]
I've released baldrick 0.1 and astropy-changelog 0.1 so moving ahead with this!

**Pull request merged**
