### PR TITLE
BUG: Do not complain of missing log if skip-changelog-checks given

### PR DESCRIPTION
**Pull request by pllim**
Fix the complain seen at astropy/astropy#8060 (PR opened against a branch without any change log)

### CODE REVIEW

**Comment by pllim** [comment]
Failures appear unrelated.

**Comment by pllim** [comment]
Maybe I'll fix those failures and even add a test. Like someone, I am also procrastinating.

**Comment by pllim** [comment]
Tests passed. Coverage increased. Shall we merge?

**Comment by bsipocz** [comment]
I would vote for merging this here and now. The issue has been solved in baldrick, but we don't have a realistic ETA when that transition can happen, so I think it's better to get the patch in here, too.

**Pull request merged**
