### PR TITLE
adding functionality to set labels

### PR DESCRIPTION
**Pull request by dr-rodriguez**
Some additional methods to IssueHandler to allow for labels to be set (#54). Also added a line in stale issues to add the 'closed-by-bot' label on issues that are auto-closed.

Also relevant to issues #65 and #66 

Tests are still needed for the new method.

### CODE REVIEW

**Comment by pllim** [comment]
@bsipocz do you want to have a look before I merge? @astrofrog are you still awake? If I don't hear by 6PM, I'll just merge as is. This LGTM. Thanks!

**Review by pllim — APPROVED** [review]

**Comment by bsipocz** [comment]
@pllim - Let's merge :)

**Comment by bsipocz** [comment]
Thanks @dr-rodriguez and @pllim!

**Comment by pllim** [comment]
Huh... I can see the "close and comment" button but I cannot see "merge".

**Comment by pllim** [comment]
Oh, it is merged already. Thanks, @bsipocz . Hahaha...

**Pull request merged**
