### PR TITLE
Do not post message if PR is closed

### LINKED ISSUE #48: Changelog-bot should not comment on closed PRs
I'm adjusting labels on closed PRs, and the bot regained some unneeded consciousness. Ideally it shouldn't comment on already closed PRs/issues.

e.g. https://github.com/astropy/astropy/pull/4423#issuecomment-333693283

### PR DESCRIPTION
**Pull request by pllim**
Fix #48.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @pllim, you were faster than me (bogged down too much with the template and ci issues). While it looked OK to me, I'm not yet familiar enough with all parts of the bot to be able to spot tricky issues.

**Comment by pllim** [comment]
How did coverage manage to decrease? I **added** tests! 😱

**Comment by bsipocz** [comment]
ahh, coveralls is not the sharpest knife in that drawer. I meant to look into other coverage services, but it's buried under other tasks...

**Comment by pllim** [comment]
No worries!

**Review by astrofrog — APPROVED** [review]
Thanks and sorry for dropping the ball on this!

**Comment by pllim** [comment]
No problem!

**Pull request merged**
